// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, breq, get, json, lang, output, promises, queries, query, queryData, saveResults, url;

  breq = require('bluereq');

  get = function(url) {
    return breq.get(url).then(function(res) {
      return res.body;
    });
  };

  Promise = require('bluebird');

  queries = require('../queries');

  saveResults = require('./save_results');

  require('colors');

  query = function(id, output) {
    return "https://quarry.wmflabs.org/run/" + id + "/output/" + output + "/json";
  };

  promises = {};

  for (lang in queries) {
    queryData = queries[lang];
    json = queryData.json, output = queryData.output;
    url = query(json, output);
    console.log((lang + " data:").grey, url);
    promises[lang] = get(url);
  }

  Promise.props(promises).then(saveResults).then(function() {
    return console.log('done!'.green);
  })["catch"](function(err) {
    return console.log('err'.red, err.stack);
  });

}).call(this);
